#! /bin/python
import os, sys, glob
import shutil
import platform

# Add BuildHelper.py directory to path
sys.path.append('../../')

from colorizer import colorizer
from BuildHelper import *

setup(ARGUMENTS)

def setupDependencies():
	### Set our libraries
	glLib = 'GL'
	glewLib = 'GLEW'
	libPThread = 'pthread'
	cefLib = 'cef'
	cefDllWrapperLib = 'cef_dll_wrapper'
	boostLogLib = 'boost_log'
	boostLogSetupLib = 'boost_log_setup'
	boostDateTimeLib = 'boost_date_time'
	boostChronoLib = 'boost_chrono'
	boostThreadLib = 'boost_thread'
	boostWaveLib = 'boost_wave'
	boostRegexLib = 'boost_regex'
	boostFilesystemLib = 'boost_filesystem'
	boostSystemLib = 'boost_system'
	boostSerializationLib = 'boost_serialization'
	
	
	if (isWindows):
		glLib = 'opengl32'
		glewLib = 'glew32'
		libPThread = ''
		cefLib = 'libcef'
		cefDllWrapperLib = 'libcef_dll_wrapper'
		boostLogLib = 'libboost_log-vc120-mt-1_55'
		boostLogSetupLib = 'libboost_log_setup-vc120-mt-1_55'
		boostDateTimeLib = 'libboost_date_time-vc120-mt-1_55'
		boostChronoLib = 'libboost_chrono-vc120-mt-1_55'
		boostThreadLib = 'libboost_thread-vc120-mt-1_55'
		boostWaveLib = 'libboost_wave-vc120-mt-1_55'
		boostRegexLib = 'libboost_regex-vc120-mt-1_55'
		boostFilesystemLib = 'libboost_filesystem-vc120-mt-1_55'
		boostSystemLib = 'libboost_system-vc120-mt-1_55'
		boostSerializationLib = 'libboost_serialization-vc120-mt-1_55'


	# Set our required libraries
	libraries.append('glr')
	libraries.append(glLib)
	libraries.append(glewLib)
	libraries.append(libPThread)
	if (buildFlags['useCef']):
		libraries.append(cefLib)
		libraries.append(cefDllWrapperLib)
	libraries.append('assimp')
	libraries.append('freeimage')
	libraries.append('sfml-system')
	libraries.append('sfml-window')
	libraries.append(boostLogLib)
	libraries.append(boostLogSetupLib)
	libraries.append(boostDateTimeLib)
	libraries.append(boostChronoLib)
	libraries.append(boostThreadLib)
	libraries.append(boostWaveLib)
	libraries.append(boostRegexLib)
	libraries.append(boostFilesystemLib)
	libraries.append(boostSystemLib)
	libraries.append(boostSerializationLib)
	
	if (not isWindows):
		# XInput for linux
		libraries.append( 'Xi' )
	
	### Set our library paths
	library_paths.append('../../' + dependenciesDirectory + 'sfml/lib')
	library_paths.append('../../' + dependenciesDirectory + 'assimp/lib')
	library_paths.append('../../' + dependenciesDirectory + 'boost/lib')
	library_paths.append('../../' + dependenciesDirectory + 'freeimage/lib')
	library_paths.append('../../' + dependenciesDirectory + 'cef3/Release')

	library_paths.append('../../build')
	library_paths.append('../../lib')
	#library_paths.append('../lib_d')

def setupEnvironment(env):
	col = colorizer()
	col.colorize(env)
	
	### Set our environment variables
	env.Append( CPPFLAGS = cpp_flags )
	env.Append( CPPDEFINES = cpp_defines )
	env.Append( CPPPATH = cpp_paths )
	env.Append( LINKFLAGS = link_flags )
	
	env.SetOption('num_jobs', buildFlags['num_jobs'])

	if isLinux:
		# Set our runtime library locations
		env.Append( RPATH = env.Literal(os.path.join('\\$$ORIGIN', '.')))
		
		# include cflags and libs for gtk+-2.0
		if (buildFlags['useCef']):
			env.ParseConfig('pkg-config --cflags --libs gtk+-2.0')

def copyAllFiles(directory, toDirectory='./build/'):
	try:
		for filename in glob.glob(os.path.join(directory, '*.*')):
			shutil.copy(filename, toDirectory)
	except:
		#print('Failed to copy cef wrapper!')
		pass

def copyResources():
	"""Copies over resources to the build directory.
	"""

	if (not os.path.exists('build')):
		os.makedirs('build')
	if (not os.path.exists('build/locales')):
		os.makedirs('build/locales')
	
	copyAllFiles('../../' + dependenciesDirectory + 'cef3/Release/')
	copyAllFiles('../../' + dependenciesDirectory + 'cef3/Resources/locales/', './build/locales/')
	
	if (isWindows):
		copyAllFiles('../../' + dependenciesDirectory + 'glew/lib/')
		copyAllFiles('../../' + dependenciesDirectory + 'freeimage/lib/')
		copyAllFiles('../../' + dependenciesDirectory + 'assimp/lib/')
		copyAllFiles('../../' + dependenciesDirectory + 'sfml/lib/')
		copyAllFiles('../../' + dependenciesDirectory + 'boost/lib/')


# Tell SCons to create our build files in the 'build' directory
VariantDir('build', 'src', duplicate=0)

# Set our source files
source_files = Glob('build/*.cpp')
source_files += Glob('build/extras/*.cpp')

setupDependencies()

### Create our environment
env = Environment(ENV = os.environ, TOOLS = [buildFlags['compiler']])
setupEnvironment(env)

# Tell SCons the program to build
env.Program('build/simple', source_files, LIBS = libraries, LIBPATH = library_paths)

### Copy all of our required resources to the build directory
copyResources()
