import os

# Tell SCons to create our build files in the 'build' directory
VariantDir('build', 'src', duplicate=0)

# Set our source files
source_files = Glob('*.cpp', '*.h')

env = Environment(ENV = os.environ, CCFLAGS=[]) 


# Set our required libraries
libraries = [
'glr',
'GL',
'GLEW',
'liblibberkelium_d',
'Xi',
'sfml-window',
'assimp',
'freeimage',
'Angelscript',
'boost_log', 
'boost_date_time', 
'boost_thread',
'boost_wave',
'boost_regex'
]

library_paths = [  
'../../build',
]

# Set our g++ compiler flags
cpp_flags = [
'-std=c++11',
'-Wall',
'-I"../../src"',
]

cpp_defines = []

if (os.name == "nt" or os.name == "win32"):
	cpp_flags.append( '-I"C:\lib\Assimp\include"' )

cpp_flags.append('-g')
cpp_defines.append('DEBUG')	
       

env.Append( CPPFLAGS = cpp_flags )
env.Append( CPPDEFINES = cpp_defines )

env.SetOption('num_jobs', 4)

# Tell SCons the program to build
env.Program('build/simple', source_files, LIBS = libraries, LIBPATH = library_paths)
